### ISSUE TITLE
dot transfer problem on polkawallet

### ISSUE THREAD

**Issue by zilio1997** [polkawallet-io/polkawallet-flutter#157]
I wanted  to transfer my dots to another address. In the homepage it gives me the dots as available because they are not staked, when I go to the screen to transfer the Dot to me from 0 dots available, therefore I cannot transfer them. How can i do to solve? thank you
![347BBDEC-87AE-49E6-AB7A-7FC36DCD41EC](https://user-images.githubusercontent.com/70485136/91666477-4bf20880-eafd-11ea-8ad6-1eddd7ca73e6.png)
![FEFBA5C5-2DA0-45B9-935F-422A940A97A0](https://user-images.githubusercontent.com/70485136/91666482-4eecf900-eafd-11ea-88ec-5ecc88994213.png)

**Comment by RomeroYang** [comment]
Thanks for your report, there's a bug on this page.

`Send to Address` may have a default value of another account in your wallet, if you have only one account, data parsing will fail. we will fix this in next release.

The most simple way to avoid this issue is to add some address in your address book, and mark it as `Observation`. after doing that, the transfer page will works well.
